### PR TITLE
Added pseudoelements PostCSS Plugin

### PR DESCRIPTION
**Pull request by magsout**
#81

### CODE REVIEW

**Comment by MoOx** [comment]
This looks perfect (except the broken build, but it's related to https://github.com/Nyalab/caniuse-api/issues/27).
I just would like one more thing: disable this when IE 8 in not in the browser scope.
Caniuse have some data on this http://caniuse.com/#search=before

Maybe we can add this in the `caniuseFeaturesMap` in order to do that? Not sure how caniuse-api handle partial support (poke @Nyalab)

**Comment by magsout** [comment]
> Maybe we can add this in the caniuseFeaturesMap in order to do that? Not sure how caniuse-api handle partial support (poke @Nyalab)

Or maybe we should detect if ie8 is passed in option.browser, if no, we pass option to false ?

**Comment by MoOx** [comment]
@magsout yeah. Maybe we should enhance this map in order to accept callback for specific features.

**Comment by magsout** [comment]
```
caniuse.isSupported('css-content', 'ie 8) => false

```

**Comment by MoOx** [comment]
So, you know what to do then ?

**Comment by magsout** [comment]
hug

**Comment by MoOx** [comment]
Can you do 2 things:
- add this to the example (ref https://github.com/cssnext/cssnext#add-a-feature)
- add the plugin link to feature list

And also update the date to tomorrow. I don't want people think it's a joke :D

**Comment by magsout** [comment]
Done.

**Comment by MoOx** [comment]
Last thing, if you can change the version in CHANGELOG to 1.2.0 (it's a feature not a patch) + bump in package.json, I will be perfect so I can just do

```console
$ git pull
$ npmpublish
```

Ref: https://github.com/MoOx/setup/blob/master/functions/npmpublish ;)

**Comment by MoOx** [comment]
And add "Close #81" in commit description ;)

**Comment by magsout** [comment]
Done ;)

**Comment by MoOx** [comment]
Build is broken for example expected output not being updated and some sourcemap fix. I will handle that.

**Comment by magsout** [comment]
after that I added?

**Comment by MoOx** [comment]
No before :)
Well for the example.css you didn't update the expected output :p

**Comment by MoOx** [comment]
I will fix the build and publish. Thanks @magsout

**Pull request merged**
