### PR TITLE
Add usage with Fly.js build tool

### PR DESCRIPTION
**Pull request by drKraken**

### CODE REVIEW

**Comment by MoOx** [comment]
Nice !
Would you be interested to move the repo under the cssnext org as well?

**Comment by drKraken** [comment]
sure, think it's more rational.

**Comment by MoOx** [comment]
You have been added to the org. Feel free to move the repo ;)

**Comment by drKraken** [comment]
done :tada:

**Comment by MoOx** [comment]
👌🏼

**Pull request merged**
