### PR TITLE
Add `config` option to CLI

### PR DESCRIPTION
**Pull request by hgl**
Feel free to change the flag name and the `input` & `output` options in the config file.

### CODE REVIEW

**Comment by MoOx** [comment]
I would more like to see a PR that cover cli and non cli usage ( #73)

**Comment by MoOx** [comment]
Note: input and output do not have their place in a generic config file

**Comment by hgl** [comment]
#73 looks like it belongs to another commit. This PR simply allows users to specify a config flag. Also you haven't settled on the file name in that issue.

cli usage is covered in the unit tests.

I will remove input and output from the config file.

**Comment by hgl** [comment]
Done. (it seems appveyor failed to install microtime, not sure how that happened.)

**Comment by MoOx** [comment]
Can you also include documentation and a line in the changelog for that (as `# Unreleased`) ?
Thanks !

**Comment by hgl** [comment]
Changelog updated. By documentation do you mean the readme file? It already contains the `To see all CLI options` section, not sure where to add the doc. Should I add a section to specifically explain the `config` option?

**Comment by MoOx** [comment]
Good point !
I will handle that from here :)
Thanks a lot.

**Comment by hgl** [comment]
Thank you for accepting the PR. :)

**Comment by MoOx** [comment]
Released in 1.1.0

**Comment by hgl** [comment]
:clap:

**Pull request merged**
