### PR TITLE
use object assign when passing options to atImport plugin

### PR DESCRIPTION
**Pull request by lionelB**
small fixes that avoid mutability error when passing options to atImport plugin

### CODE REVIEW

**Comment by MoOx** [comment]
Should be part of postcss-import plugin ? I created yesterday an issue per your comment https://github.com/postcss/postcss-import/issues/43
Or we should do that for all plugin. And if a object is has been frozen, I guess Object.assign is not enough because it's only one level deep. Should be a clone... no ?

**Comment by lionelB** [comment]
WTF appveyor

**Comment by MoOx** [comment]
nevermind. Thanks for updating the PR, I will merge and release soon

**Comment by MoOx** [comment]
Released as 1.6.0 !

**Comment by MoOx** [comment]
appveyor is happy now https://ci.appveyor.com/project/MoOx/cssnext/build/201

**Pull request merged**
