### PR TITLE
Update to stable chokidar.

### PR DESCRIPTION
**Pull request by paulmillr**
That's it. It is much more stable.

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks for this.
Will this fix https://github.com/paulmillr/chokidar/issues/258 ?
I didn't take some time to reproduce that sorry :)

**Comment by paulmillr** [comment]
@MoOx we've made some improvements to `unwatch` in 1.0.1 — maybe. I'll test it on my machine.

**Comment by MoOx** [comment]
Awesome.
Patch released as 1.2.2 :)

**Comment by MoOx** [comment]
Thanks !

**Pull request merged**
