### PR TITLE
Update setup.md

### PR DESCRIPTION
**Pull request by pensierinmusica**
Updating docs according to https://github.com/cssnext/cssnext/issues/202

### CODE REVIEW

**Comment by MoOx** [comment]
Thanks. I will wait to upgrade cssnext itself to handle this :)

**Comment by pensierinmusica** [comment]
I see. Could you please give me more details? As I'm currently using `cssnext` in a project with `gulp-postcss` and had to switch to `postcss-cssnext` after upgrading packages.

**Comment by MoOx** [comment]
All of the story is in https://github.com/cssnext/cssnext/issues/202 for now.

Did you read at the postcss-cssnext README https://github.com/cssnext/postcss-cssnext#readme ?
You should find some answers ;)

**Comment by pensierinmusica** [comment]
I already read all of #202 and https://github.com/cssnext/postcss-cssnext#readme.

I still don't understand whether with `gulp-postcss` I should use `cssnext` or `postcss-cssnext`. Please note that I am using CSS imports in my stylesheets.

Imho, the docs you mentioned are not clear enough on this point.

**Comment by MoOx** [comment]
I don't know what to say. The "Why postcss-cssnext ? What is the difference with cssnext ?" section should be enough for you to understand why.
cssnext has a cli and bring more that it should for a simple plugin.
cssnext was designed as a tool for end user. Usage as a postcss plugin was just a convenience. But since everybody is using it as a postcss plugin (and it's creating some confusion), I think (and some others too) it's a better idea to have a simple but focused plugin like postcss-cssnext).
Related https://github.com/cssnext/cssnext/issues/208

**Comment by MoOx** [comment]
Everything will be "official" in the next major version of cssnext, but it's need some attentions to be done.

**Comment by pensierinmusica** [comment]
I see now, do you mind if I include a bit of the explanation you just gave me in the `postcss-cssnext` readme? Imho this would make things more clear for other people too.

**Comment by MoOx** [comment]
👌🏼

**Pull request closed without merging**
