### PR TITLE
Prevent exiting on errors when using --watch option

### LINKED ISSUE #68: `cssnext --watch` exits when there is an error
If in launch `cssnext` with the `--watch` option and if there is an error in my source CSS, the whole process crashes because of the thrown exception and I have to launch it again from the command line.

IMO it would be much more useful to continue waiting for changes so the user has the opportunity to fix his mistakes without having to relaunch `cssnext`.

### PR DESCRIPTION
**Pull request by madx**
Closes #68

### CODE REVIEW

**Comment by madx** [comment]
Wait, I forgot the tests! :-)

**Comment by madx** [comment]
Here they are :-)

**Comment by MoOx** [comment]
Dude, tests are broken and Travis & Appveyor :p

**Comment by MoOx** [comment]
Btw, if you touch something, please bump package.json (patch) & update changelog too ^^

**Comment by madx** [comment]
I noticed that the test failed but it's not coming from the one I added, it's a stylistic issue in the benchmarks tests

I'll update the changelog but do you want me to update the patch version number as well? You release 1 patch version per commit?

**Comment by MoOx** [comment]
Ok nevermind, I'll fix the lint issue since it's because of me, then merge your PR and release as patch, tonight or tomorrow.

**Comment by madx** [comment]
:shipit: :fireworks: 

I can push a pre-updated changelog if you want

**Pull request merged**
